### ISSUE TITLE
soon

### ISSUE THREAD

**Issue by inexist3nce** [cxreet/chromium-debloating#1]
according to [Merriam-Webster's dictionary](https://www.merriam-webster.com/dictionary/soon), the word _soon_ has three definitions:
1. without undue time lapse : _BEFORE LONG_
2. in a prompt manner : _SPEEDILY_
3. in agreement with one's choice or preference : _WILLINGLY_

this explains that "soon" is roughly "a short period of time".

the [README.md](https://github.com/cxreet/chromium-debloating/blob/master/README.md) file in this repository explains that the source file will be released "soon", which is not true, since this repository was created 6 months and 23 days ago. additionally, the _slimium_ paper was released 113 days ago. in my opinion, these are *far* from "soon".

will the source code ever be released?

**Comment by cxreet** [comment]
Hi inexist3nce,

Sorry for the delay. It's released now, please check the README.
And, **DO NOT TALK LIKE A EUNUCH IF YOU ARE NOT!**
